# Generated by Django 6.1.1 on 2026-09-25 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام استان')),
                ('code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='کد استان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NationalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_dashboard', 'مشاهده داشبورد'), ('view_province', 'مشاهده استان'), ('view_district', 'مشاهده منطقه'), ('view_school', 'مشاهده مدرسه'), ('view_reports', 'مشاهده گزارش\u200cها'), ('export_data', 'خروجی داده'), ('update_policy', 'به\u200cروزرسانی سیاست'), ('view_api', 'استفاده از API')], max_length=50, verbose_name='عملیات')),
                ('scope', models.CharField(default='national', max_length=20, verbose_name='محدوده')),
                ('scope_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه محدوده')),
                ('scope_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام محدوده')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ عملیات کشوری',
                'verbose_name_plural': 'لاگ\u200cهای عملیات کشوری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NationalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL, verbose_name='به\u200cروزرسانی توسط')),
            ],
            options={
                'verbose_name': 'سیست عمومی',
                'verbose_name_plural': 'سیاست\u200cهای عمومی',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منطقه')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='کد منطقه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='national.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'منطقه آموزشی',
                'verbose_name_plural': 'مناطق آموزشی',
                'ordering': ['province', 'name'],
                'unique_together': {('province', 'name')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مدرسه')),
                ('school_type', models.CharField(choices=[('public', 'دولتی'), ('private', 'غیرانتفاعی'), ('technical', 'فنی و حرفه\u200cای'), ('special', 'استثنایی')], default='public', max_length=20, verbose_name='نوع مدرسه')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='national.district', verbose_name='منطقه آموزشی')),
                ('principal', models.ForeignKey(blank=True, limit_choices_to={'role': 'principal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_schools', to=settings.AUTH_USER_MODEL, verbose_name='مدیر مدرسه')),
            ],
            options={
                'verbose_name': 'مدرسه',
                'verbose_name_plural': 'مدارس',
                'ordering': ['district__province', 'district', 'name'],
            },
        ),
    ]
