# Generated by Django 6.1.1 on 2026-09-26 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_classroom_school'),
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('topic', models.CharField(blank=True, default='', max_length=200, verbose_name='موضوع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('in_progress', 'در حال برگزاری'), ('completed', 'تکمیل شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدت (دقیقه)')),
                ('total_score', models.FloatField(default=20.0, verbose_name='نمره کل')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='ترتیب تصادفی سوالات')),
                ('show_result', models.BooleanField(default=True, verbose_name='نمایش نتیجه به دانش\u200cآموز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='dashboard.classroom', verbose_name='کلاس')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='dashboard.classsession', verbose_name='جلسه مرتبط')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'ارزیابی',
                'verbose_name_plural': 'ارزیابی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='دلیل پیشنهاد')),
                ('details', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='شواهد (داده\u200cهای پشتیبان)')),
                ('status', models.CharField(choices=[('submitted', 'ارسال شده'), ('reviewed', 'بررسی شده'), ('converted', 'تبدیل به پرونده'), ('rejected', 'رد شده')], default='submitted', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_suggestions', to='dashboard.classroom', verbose_name='کلاس')),
                ('converted_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_suggestions', to='school.followupcase', verbose_name='پرونده مرتبط')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'پیشنهاد پیگیری معلم',
                'verbose_name_plural': 'پیشنهادهای پیگیری معلمان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='شرح تکلیف')),
                ('topic', models.CharField(blank=True, default='', max_length=200, verbose_name='موضوع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('closed', 'بسته شده'), ('archived', 'بایگانی شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('deadline', models.DateTimeField(verbose_name='مهلت ارسال')),
                ('max_score', models.FloatField(default=20.0, verbose_name='حداکثر نمره')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/attachments/', verbose_name='پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='dashboard.classroom', verbose_name='کلاس')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='dashboard.classsession', verbose_name='جلسه مرتبط')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی شده'), ('active', 'فعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20, verbose_name='وضعیت جلسه')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='درس')),
                ('learning_objectives', models.TextField(blank=True, default='', verbose_name='اهداف یادگیری')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='dashboard.classsession', verbose_name='جلسه')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_extensions', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'اطلاعات تکمیلی جلسه',
                'verbose_name_plural': 'اطلاعات تکمیلی جلسات',
            },
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('assessment', 'ارزیابی'), ('homework', 'تکلیف'), ('participation', 'مشارکت'), ('general', 'عمومی')], default='general', max_length=20, verbose_name='نوع بازخورد')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='نمره')),
                ('content', models.TextField(verbose_name='متن بازخورد')),
                ('is_ai_draft', models.BooleanField(default=False, verbose_name='پیش\u200cنویس هوش مصنوعی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='teacher.assessment', verbose_name='ارزیابی مرتبط')),
                ('related_homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='teacher.homework', verbose_name='تکلیف مرتبط')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'بازخورد معلم',
                'verbose_name_plural': 'بازخوردهای معلمان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن یادداشت')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='حساس (فقط با مجوز قابل مشاهده)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to='dashboard.classroom', verbose_name='کلاس مرتبط')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notes', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'یادداشت معلم',
                'verbose_name_plural': 'یادداشت\u200cهای معلمان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('score', models.FloatField(default=1.0, verbose_name='نمره سوال')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=10, verbose_name='سطح دشواری')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher.assessment', verbose_name='ارزیابی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_links', to='dashboard.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'سوال ارزیابی',
                'verbose_name_plural': 'سوالات ارزیابی\u200cها',
                'ordering': ['order'],
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'ارسال نشده'), ('submitted', 'ارسال شده'), ('late', 'ارسال با تأخیر'), ('reviewed', 'بررسی شده'), ('returned', 'بازگردانده شده')], default='not_submitted', max_length=20, verbose_name='وضعیت')),
                ('content', models.TextField(blank=True, default='', verbose_name='متن پاسخ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/submissions/', verbose_name='فایل ارسالی')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='نمره')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='بازخورد معلم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher.homework', verbose_name='تکلیف')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ارسال تکلیف',
                'verbose_name_plural': 'ارسال\u200cهای تکلیف',
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('high', 'بالا'), ('medium', 'متوسط'), ('low', 'کم')], max_length=10, verbose_name='سطح مشارکت')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='امتیاز مشارکت (0-100)')),
                ('source', models.CharField(choices=[('manual', 'ثبت دستی معلم'), ('question_response', 'پاسخ به سوال'), ('assessment', 'ارزیابی'), ('homework', 'تکلیف'), ('class_activity', 'فعالیت کلاسی')], default='manual', max_length=30, verbose_name='منبع ثبت')),
                ('note', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='dashboard.classsession', verbose_name='جلسه')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_participations', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'رکورد مشارکت',
                'verbose_name_plural': 'رکوردهای مشارکت',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'student', 'source')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(choices=[('a', 'الف'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1, verbose_name='گزینه انتخابی')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='نمره')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='teacher.assessment', verbose_name='ارزیابی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_student_responses', to='dashboard.question', verbose_name='سوال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز به ارزیابی',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان به ارزیابی\u200cها',
                'unique_together': {('assessment', 'student', 'question')},
            },
        ),
    ]
