# Generated by Django 6.1.1 on 2026-09-26 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_classroom_school'),
        ('national', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(max_length=30, verbose_name='وضعیت جدید')),
                ('reason', models.TextField(verbose_name='دلیل تغییر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='dashboard.attendancerecord', verbose_name='رکورد حضور')),
                ('attendance_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='dashboard.attendanceresponse', verbose_name='پاسخ حضور')),
                ('overridden_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_overrides', to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_overrides', to='national.school', verbose_name='مدرسه')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_overrides', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'لاگ تغییر حضور',
                'verbose_name_plural': 'لاگ\u200cهای تغییر حضور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpCase',
            fields=[
                ('case_number', models.AutoField(primary_key=True, serialize=False, verbose_name='شماره پرونده')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('ABSENCE', 'غیبت'), ('PARTICIPATION', 'مشارکت'), ('PERFORMANCE', 'عملکرد تحصیلی'), ('BEHAVIOR', 'رفتاری'), ('VERIFICATION', 'احراز هویت'), ('SCHEDULE', 'برنامه'), ('OTHER', 'سایر')], default='OTHER', max_length=30, verbose_name='دسته\u200cبندی')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد'), ('URGENT', 'فوری')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('IN_REVIEW', 'در حال بررسی'), ('ASSIGNED', 'ارجاع داده شده'), ('RESOLVED', 'حل شده'), ('DISMISSED', 'رد شده')], default='OPEN', max_length=20, verbose_name='وضعیت')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='مهلت پیگیری')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حل')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='یادداشت حل')),
                ('escalated', models.BooleanField(default=False, verbose_name='ارجاع به مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followup_cases', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع به')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_cases', to='dashboard.classroom', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_followup_cases', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_cases', to='national.school', verbose_name='مدرسه')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_cases', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پرونده پیگیری',
                'verbose_name_plural': 'پرونده\u200cهای پیگیری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('DETECTED', 'شناسایی شده'), ('REVIEWED', 'بررسی شده'), ('CONTACTED', 'تماس گرفته شده'), ('CONFIRMED', 'تأیید شده'), ('ESCALATED', 'ارجاع به مدیر'), ('RESOLVED', 'حل شده')], default='DETECTED', max_length=20, verbose_name='وضعیت بررسی')),
                ('contact_note', models.TextField(blank=True, default='', verbose_name='یادداشت تماس')),
                ('review_date', models.DateField(verbose_name='تاریخ غیبت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_reviews', to='dashboard.attendancerecord', verbose_name='رکورد حضور')),
                ('attendance_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_reviews', to='dashboard.attendanceresponse', verbose_name='پاسخ حضور')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_absences', to=settings.AUTH_USER_MODEL, verbose_name='بررسی توسط')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reviews', to='national.school', verbose_name='مدرسه')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reviews', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_reviews', to='school.followupcase', verbose_name='پرونده مرتبط')),
            ],
            options={
                'verbose_name': 'بررسی غیبت',
                'verbose_name_plural': 'بررسی\u200cهای غیبت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpCaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_notes', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='school.followupcase', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'یادداشت پرونده',
                'verbose_name_plural': 'یادداشت\u200cهای پرونده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ABSENCE_SPIKE', 'افزایش غیبت'), ('PARTICIPATION_DROP', 'افت مشارکت'), ('PERFORMANCE_DROP', 'افت عملکرد'), ('SUSPICIOUS_ATTENDANCE', 'حضور مشکوک'), ('NO_ATTENDANCE_RECORDED', 'کلاس بدون حضور و غیاب'), ('INCOMPLETE_SESSION', 'جلسه ناقص'), ('FACE_VERIFICATION_FAILURE', 'خطای احراز هویت'), ('SCHEDULE_CONFLICT', 'تداخل برنامه'), ('PENDING_REVIEW', 'در انتظار بررسی'), ('UNRESOLVED_FOLLOWUP', 'پیگیری حل نشده')], max_length=40, verbose_name='نوع هشدار')),
                ('severity', models.CharField(choices=[('CRITICAL', 'بحرانی'), ('WARNING', 'هشدار'), ('INFO', 'اطلاع')], default='WARNING', max_length=10, verbose_name='شدت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(blank=True, default='', verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='حل شده')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_alerts', to='dashboard.classroom', verbose_name='کلاس مرتبط')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='حل توسط')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='national.school', verbose_name='مدرسه')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_alerts', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز مرتبط')),
            ],
            options={
                'verbose_name': 'هشدار مدرسه',
                'verbose_name_plural': 'هشدارهای مدرسه',
                'ordering': ['-is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('attendance_override', 'تغییر حضور و غیاب'), ('student_status_change', 'تغییر وضعیت دانش\u200cآموز'), ('class_change', 'تغییر کلاس'), ('teacher_assignment', 'انتصاب معلم'), ('assistant_assignment', 'انتصاب معاون'), ('schedule_approval', 'تأیید برنامه'), ('school_setting_change', 'تغییر تنظیمات مدرسه'), ('followup_resolution', 'حل پرونده پیگیری'), ('followup_creation', 'ایجاد پرونده پیگیری'), ('followup_assignment', 'ارجاع پرونده'), ('student_class_assign', 'انتصاب دانش\u200cآموز به کلاس'), ('view_dashboard', 'مشاهده داشبورد'), ('view_reports', 'مشاهده گزارش\u200cها'), ('export_data', 'خروجی داده')], max_length=40, verbose_name='عملیات')),
                ('object_type', models.CharField(blank=True, default='', max_length=100, verbose_name='نوع شیء')),
                ('object_id', models.CharField(blank=True, default='', max_length=50, verbose_name='شناسه شیء')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='مقادیر قبلی')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='مقادیر جدید')),
                ('reason', models.TextField(blank=True, default='', verbose_name='دلیل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='national.school', verbose_name='مدرسه')),
            ],
            options={
                'verbose_name': 'لاگ عملیات مدرسه',
                'verbose_name_plural': 'لاگ\u200cهای عملیات مدرسه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, default='1404-1405', max_length=20, verbose_name='سال تحصیلی')),
                ('absence_warning_threshold', models.FloatField(default=20.0, verbose_name='آستانه هشدار غیبت (٪)')),
                ('participation_warning_threshold', models.FloatField(default=40.0, verbose_name='آستانه هشدار مشارکت (٪)')),
                ('performance_warning_threshold', models.FloatField(default=50.0, verbose_name='آستانه هشدار عملکرد (٪)')),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15, verbose_name='آستانه تأخیر (دقیقه)')),
                ('face_verification_required', models.BooleanField(default=True, verbose_name='الزام احراز هویت چهره')),
                ('auto_mark_absent_on_deadline', models.BooleanField(default=True, verbose_name='ثبت خودکار غیبت پس از مهلت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='national.school', verbose_name='مدرسه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='به\u200cروزرسانی توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات مدرسه',
                'verbose_name_plural': 'تنظیمات مدارس',
            },
        ),
        migrations.CreateModel(
            name='SchoolTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('TODO', 'در انتظار'), ('IN_PROGRESS', 'در حال انجام'), ('DONE', 'انجام شده')], default='TODO', max_length=20, verbose_name='وضعیت')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='مهلت')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_school_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='school.followupcase', verbose_name='پرونده مرتبط')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='national.school', verbose_name='مدرسه')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(choices=[('principal', 'مدیر مدرسه'), ('assistant', 'معاون')], max_length=20, verbose_name='نقش')),
                ('assistant_type', models.CharField(blank=True, choices=[('EXECUTIVE', 'اجرایی'), ('EDUCATIONAL', 'آموزشی'), ('CULTURAL', 'پرورشی'), ('TECHNICAL', 'فنی'), ('GENERAL', 'عمومی'), ('CUSTOM', 'سفارشی')], default='', help_text='فقط برای نقش معاون', max_length=20, verbose_name='نوع معاونت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='national.school', verbose_name='مدرسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'انتصاب کارکنان مدرسه',
                'verbose_name_plural': 'انتصاب\u200cهای کارکنان مدرسه',
                'ordering': ['-is_active', 'staff_role', 'assistant_type'],
                'unique_together': {('user', 'school', 'staff_role', 'assistant_type')},
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('TRANSFERRED', 'منتقل شده'), ('GRADUATED', 'فارغ\u200cالتحصیل')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('reason', models.TextField(blank=True, default='', verbose_name='دلیل تغییر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='national.school', verbose_name='مدرسه')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_statuses', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'وضعیت دانش\u200cآموز در مدرسه',
                'verbose_name_plural': 'وضعیت\u200cهای دانش\u200cآموزان در مدارس',
                'unique_together': {('student', 'school')},
            },
        ),
    ]
