# Generated by Django 6.1.1 on 2026-09-11 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان حضور و غیاب')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب')], default='present', max_length=10, verbose_name='وضعیت')),
                ('attendance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboard.attendancecheck', verbose_name='حضور و غیاب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'رکورد حضور',
                'verbose_name_plural': 'رکوردهای حضور',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('subject', models.CharField(max_length=100, verbose_name='درس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(related_name='enrolled_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ جلسه')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='موضوع جلسه')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.classroom', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'جلسه کلاس',
                'verbose_name_plural': 'جلسات کلاس',
            },
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_checks', to='dashboard.classsession', verbose_name='جلسه'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('choice_a', models.CharField(max_length=200, verbose_name='گزینه الف')),
                ('choice_b', models.CharField(max_length=200, verbose_name='گزینه ب')),
                ('choice_c', models.CharField(max_length=200, verbose_name='گزینه ج')),
                ('choice_d', models.CharField(max_length=200, verbose_name='گزینه د')),
                ('correct_answer', models.CharField(choices=[('a', 'الف'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1, verbose_name='پاسخ صحیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.classroom', verbose_name='کلاس')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.classsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(choices=[('a', 'الف'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1, verbose_name='گزینه انتخابی')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.question', verbose_name='سوال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان',
            },
        ),
    ]
