# Generated by Django 6.1.1 on 2026-09-25 13:33

import dashboard.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان حضور و غیاب')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب')], default='present', max_length=10, verbose_name='وضعیت')),
                ('attendance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboard.attendancecheck', verbose_name='حضور و غیاب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'رکورد حضور',
                'verbose_name_plural': 'رکوردهای حضور',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('face_only', 'فقط حضور و غیاب'), ('question_only', 'فقط سوال'), ('face_and_question', 'حضور و غیاب + سوال')], default='face_only', max_length=30, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('finished', 'پایان یافته'), ('canceled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('face_time_seconds', models.PositiveIntegerField(default=120, verbose_name='زمان اسکن چهره (ثانیه)')),
                ('face_deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت اسکن چهره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'درخواست حضور و غیاب / سوال',
                'verbose_name_plural': 'درخواست\u200cهای حضور و غیاب / سوال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.FileField(blank=True, null=True, upload_to='attendance/captured/', validators=[dashboard.validators.validate_image_file], verbose_name='تصویر گرفته\u200cشده')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='درصد تطابق')),
                ('auto_status', models.CharField(choices=[('pending', 'در انتظار'), ('present', 'حاضر'), ('suspicious', 'مشکوک'), ('absent_mismatch', 'عدم تطابق'), ('no_response', 'عدم پاسخ'), ('not_applicable', 'نامرتبط')], default='pending', max_length=20, verbose_name='وضعیت خودکار')),
                ('final_status', models.CharField(choices=[('pending', 'در انتظار'), ('present', 'حاضر'), ('absent', 'غایب'), ('not_applicable', 'نامرتبط')], default='pending', max_length=20, verbose_name='وضعیت نهایی')),
                ('face_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال اسکن')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('face_verified', models.BooleanField(blank=True, null=True, verbose_name='چهره تایید شده')),
                ('face_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت چهره')),
                ('similarity_score', models.FloatField(blank=True, null=True, verbose_name='امتیاز تطبیق')),
                ('liveness_score', models.FloatField(blank=True, null=True, verbose_name='امتیاز لایونس')),
                ('liveness_status', models.CharField(blank=True, default='', max_length=20, verbose_name='وضعیت لایونس')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='دلیل ناموفق بودن')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('attendance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.attendancerequest', verbose_name='درخواست')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_responses', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_responses', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ حضور و غیاب',
                'verbose_name_plural': 'پاسخ\u200cهای حضور و غیاب',
                'ordering': ['-created_at'],
                'unique_together': {('attendance_request', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('subject', models.CharField(max_length=100, verbose_name='درس')),
                ('grade', models.CharField(choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], default='10', max_length=2, verbose_name='پایه تحصیلی')),
                ('field', models.CharField(choices=[('computer', 'کامپیوتر'), ('electrical', 'برق'), ('mechanical', 'مکانیک'), ('accounting', 'حسابداری'), ('math', 'ریاضی'), ('experimental', 'تجربی'), ('humanities', 'انسانی')], default='math', max_length=20, verbose_name='رشته تحصیلی')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='نام معلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر معلم (اختیاری)')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='dashboard.classroom', verbose_name='کلاس'),
        ),
        migrations.CreateModel(
            name='AIGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, verbose_name='پرامپت معلم')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='مبحث')),
                ('requested_count', models.PositiveSmallIntegerField(default=5, verbose_name='تعداد سوال')),
                ('default_timer_seconds', models.PositiveIntegerField(default=300, verbose_name='زمان پیش\u200cفرض هر سوال (ثانیه)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('raw_response', models.TextField(blank=True, verbose_name='پاسخ خام هوش مصنوعی')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to='dashboard.classroom', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'درخواست تولید سوال با هوش مصنوعی',
                'verbose_name_plural': 'درخواست\u200cهای تولید سوال با هوش مصنوعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ جلسه')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='موضوع جلسه')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.classroom', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'جلسه کلاس',
                'verbose_name_plural': 'جلسات کلاس',
            },
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='dashboard.classsession', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='attendancecheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_checks', to='dashboard.classsession', verbose_name='جلسه'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='approved', max_length=10, verbose_name='وضعیت بررسی')),
                ('source', models.CharField(choices=[('ai', 'هوش مصنوعی'), ('manual', 'دستی')], default='manual', max_length=10, verbose_name='منبع سوال')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='مبحث')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('choice_a', models.CharField(max_length=200, verbose_name='گزینه الف')),
                ('choice_b', models.CharField(max_length=200, verbose_name='گزینه ب')),
                ('choice_c', models.CharField(max_length=200, verbose_name='گزینه ج')),
                ('choice_d', models.CharField(max_length=200, verbose_name='گزینه د')),
                ('correct_answer', models.CharField(choices=[('a', 'الف'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1, verbose_name='پاسخ صحیح')),
                ('timer_seconds', models.PositiveIntegerField(default=300, verbose_name='زمان پاسخ (ثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to='dashboard.aigenerationjob', verbose_name='درخواست هوش مصنوعی')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.classroom', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.classsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRequestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('timer_seconds', models.PositiveIntegerField(default=300, verbose_name='زمان پاسخ (ثانیه)')),
                ('attendance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_questions', to='dashboard.attendancerequest', verbose_name='درخواست')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_links', to='dashboard.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'سوال درخواست',
                'verbose_name_plural': 'سوالات درخواست\u200cها',
                'ordering': ['order', 'id'],
                'unique_together': {('attendance_request', 'question')},
            },
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='attendance_requests', through='dashboard.AttendanceRequestQuestion', to='dashboard.question', verbose_name='سوالات'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(choices=[('a', 'الف'), ('b', 'ب'), ('c', 'ج'), ('d', 'د')], max_length=1, verbose_name='گزینه انتخابی')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='dashboard.attendancerequest', verbose_name='درخواست حضور / سوال')),
                ('attendance_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='dashboard.attendanceresponse', verbose_name='پاسخ حضور مرتبط')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dashboard.question', verbose_name='سوال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReferencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students/reference/', validators=[dashboard.validators.validate_image_file], verbose_name='تصویر مرجع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reference_photos', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'عکس مرجع دانش\u200cآموز',
                'verbose_name_plural': 'عکس\u200cهای مرجع دانش\u200cآموزان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه')], max_length=10, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره اتاق/کلاس')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.classroom', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه\u200cهای هفتگی',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
