# Generated by Django 6.1.1 on 2026-09-11 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_weeklyschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='field',
            field=models.CharField(choices=[('computer', 'کامپیوتر'), ('electrical', 'برق'), ('mechanical', 'مکانیک'), ('accounting', 'حسابداری'), ('math', 'ریاضی'), ('experimental', 'تجربی'), ('humanities', 'انسانی')], default='math', max_length=20, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], default='10', max_length=2, verbose_name='پایه تحصیلی'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='نام معلم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر معلم (اختیاری)'),
        ),
    ]
