# Generated by Django 6.1.1 on 2026-09-12 10:05

import dashboard.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_classroom_field_classroom_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['-answered_at'], 'verbose_name': 'پاسخ دانش\u200cآموز', 'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان'},
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('ai', 'هوش مصنوعی'), ('manual', 'دستی')], default='manual', max_length=10, verbose_name='منبع سوال'),
        ),
        migrations.AddField(
            model_name='question',
            name='timer_seconds',
            field=models.PositiveIntegerField(default=300, verbose_name='زمان پاسخ (ثانیه)'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='مبحث'),
        ),
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.classsession', verbose_name='جلسه'),
        ),
        migrations.CreateModel(
            name='AIGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='ai_pdfs/', validators=[dashboard.validators.validate_pdf_file], verbose_name='فایل PDF')),
                ('prompt', models.TextField(blank=True, verbose_name='پرامپت معلم')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='مبحث')),
                ('requested_count', models.PositiveSmallIntegerField(default=5, verbose_name='تعداد سوال')),
                ('default_timer_seconds', models.PositiveIntegerField(default=300, verbose_name='زمان پیش\u200cفرض هر سوال (ثانیه)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('raw_response', models.TextField(blank=True, verbose_name='پاسخ خام هوش مصنوعی')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to='dashboard.classroom', verbose_name='کلاس')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'درخواست تولید سوال با هوش مصنوعی',
                'verbose_name_plural': 'درخواست\u200cهای تولید سوال با هوش مصنوعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='ai_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to='dashboard.aigenerationjob', verbose_name='درخواست هوش مصنوعی'),
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('face_only', 'فقط حضور و غیاب'), ('question_only', 'فقط سوال'), ('face_and_question', 'حضور و غیاب + سوال')], default='face_only', max_length=30, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('finished', 'پایان یافته'), ('canceled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('face_time_seconds', models.PositiveIntegerField(default=120, verbose_name='زمان اسکن چهره (ثانیه)')),
                ('face_deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت اسکن چهره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='dashboard.classroom', verbose_name='کلاس')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='dashboard.classsession', verbose_name='جلسه')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'درخواست حضور و غیاب / سوال',
                'verbose_name_plural': 'درخواست\u200cهای حضور و غیاب / سوال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attendance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='dashboard.attendancerequest', verbose_name='درخواست حضور / سوال'),
        ),
        migrations.CreateModel(
            name='AttendanceRequestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('timer_seconds', models.PositiveIntegerField(default=300, verbose_name='زمان پاسخ (ثانیه)')),
                ('attendance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_questions', to='dashboard.attendancerequest', verbose_name='درخواست')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_links', to='dashboard.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'سوال درخواست',
                'verbose_name_plural': 'سوالات درخواست\u200cها',
                'ordering': ['order', 'id'],
                'unique_together': {('attendance_request', 'question')},
            },
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='attendance_requests', through='dashboard.AttendanceRequestQuestion', to='dashboard.question', verbose_name='سوالات'),
        ),
        migrations.CreateModel(
            name='AttendanceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.FileField(blank=True, null=True, upload_to='attendance/captured/', validators=[dashboard.validators.validate_image_file], verbose_name='تصویر گرفته\u200cشده')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='درصد تطابق')),
                ('auto_status', models.CharField(choices=[('pending', 'در انتظار'), ('present', 'حاضر'), ('suspicious', 'مشکوک'), ('absent_mismatch', 'عدم تطابق'), ('no_response', 'عدم پاسخ'), ('not_applicable', 'نامرتبط')], default='pending', max_length=20, verbose_name='وضعیت خودکار')),
                ('final_status', models.CharField(choices=[('pending', 'در انتظار'), ('present', 'حاضر'), ('absent', 'غایب'), ('not_applicable', 'نامرتبط')], default='pending', max_length=20, verbose_name='وضعیت نهایی')),
                ('face_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال اسکن')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('attendance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.attendancerequest', verbose_name='درخواست')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_responses', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_responses', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ حضور و غیاب',
                'verbose_name_plural': 'پاسخ\u200cهای حضور و غیاب',
                'ordering': ['-created_at'],
                'unique_together': {('attendance_request', 'student')},
            },
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attendance_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='dashboard.attendanceresponse', verbose_name='پاسخ حضور مرتبط'),
        ),
        migrations.CreateModel(
            name='StudentReferencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students/reference/', validators=[dashboard.validators.validate_image_file], verbose_name='تصویر مرجع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reference_photos', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'عکس مرجع دانش\u200cآموز',
                'verbose_name_plural': 'عکس\u200cهای مرجع دانش\u200cآموزان',
                'ordering': ['-created_at'],
            },
        ),
    ]
