# Generated by Django 6.1.1 on 2026-09-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_question_options_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='review_status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='approved', max_length=10, verbose_name='وضعیت بررسی'),
        ),
    ]
