# Generated by Django 6.1.1 on 2026-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_question_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceresponse',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cها'),
        ),
        migrations.AddField(
            model_name='attendanceresponse',
            name='face_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='وضعیت چهره'),
        ),
        migrations.AddField(
            model_name='attendanceresponse',
            name='face_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='چهره تایید شده'),
        ),
        migrations.AddField(
            model_name='attendanceresponse',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='دلیل ناموفق بودن'),
        ),
        migrations.AddField(
            model_name='attendanceresponse',
            name='liveness_score',
            field=models.FloatField(blank=True, null=True, verbose_name='امتیاز لایونس'),
        ),
        migrations.AddField(
            model_name='attendanceresponse',
            name='liveness_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='وضعیت لایونس'),
        ),
        migrations.AddField(
            model_name='attendanceresponse',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='امتیاز تطبیق'),
        ),
    ]
