# Generated by Django 6.1.1 on 2026-09-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_attendanceresponse_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigenerationjob',
            name='pdf_file',
        ),
    ]
