# Generated by Django 6.1.1 on 2026-09-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('national', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='national.province', verbose_name='استان اختصاصی (برای مسئول استانی)'),
        ),
    ]
