# Generated by Django 6.1.1 on 2026-09-11 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name='نام مادر')),
                ('parent_phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس والدین')),
                ('parent_phone_2', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس اضطراری')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره موبایل دانش\u200cآموز')),
                ('address', models.TextField(blank=True, verbose_name='آدرس منزل')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='گروه خونی')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='بیماری\u200cهای خاص/حساسیت\u200cها')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='مدرسه قبلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پروفایل دانش\u200cآموز',
                'verbose_name_plural': 'پروفایل\u200cهای دانش\u200cآموزان',
            },
        ),
    ]
