"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sh%rgv3)_otk3jg=gp+vfh41x2-4m$n-oy2o12$pnu*_ya5@7x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', '192.168.1.20', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # اپلیکیشن‌های محلی
    'accounts.apps.AccountsConfig',
    'dashboard.apps.DashboardConfig',
    
    # پکیج‌های جانبی
    'django_bootstrap5',

    'face.apps.FaceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# تنظیمات کاربر سفارشی
AUTH_USER_MODEL = 'accounts.User'

# تنظیمات تمپلیت‌ها
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # دایرکتوری اصلی تمپلیت‌ها
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# زبان و منطقه زمانی
LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'


# آدرس‌های مربوط به احراز هویت
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'




# =====================================================================
# تنظیمات جدید احراز هویت چهره برای حضور و غیاب
# =====================================================================

# فعال/غیرفعال کردن کل سرویس چهره
FACE_AI_ENABLED = True

# حالت ماک برای توسعه/تست بدون مدل واقعی
# برای تست بدون دانلود مدل، مقدار را True کنید.
FACE_AI_MOCK = False

# دایرکتوری مدل‌ها
FACE_MODEL_DIR = BASE_DIR / 'models'

# مدل‌های تشخیص/بازشناسی
FACE_DETECTION_MODEL = 'buffalo_l'
FACE_RECOGNITION_MODEL = 'buffalo_l'

# آستانه تطبیق چهره
# این مقدار صرفاً برای توسعه/تست است و بعداً باید با داده واقعی کالیبره شود.
FACE_MATCH_THRESHOLD = 0.45

# حداقل/حداکثر تصاویر مرجع
FACE_MIN_REFERENCE_IMAGES = 3
FACE_MAX_REFERENCE_IMAGES = 5

# حداقل اندازه چهره و تنظیمات کیفیت
FACE_MIN_FACE_SIZE = 80
FACE_MAX_BLUR_THRESHOLD = 100.0
FACE_MIN_BRIGHTNESS = 40.0
FACE_MAX_BRIGHTNESS = 220.0

# لایونس
FACE_LIVENESS_ENABLED = True
FACE_MIN_FRAMES_FOR_LIVENESS = 3

# روش تجمیع تطبیق:
# MAX | TOP_K_MEAN | CENTROID
# مقادیر فارسی قبلی هم همچنان پشتیبانی می‌شوند.
FACE_MATCH_AGGREGATION_METHOD = 'MAX'
FACE_MATCH_TOP_K = 2

# محدودیت‌های جدید اسکن حضور
FACE_MAX_ATTEMPTS = 3
FACE_MIN_FRAMES = 5
FACE_MAX_FRAMES = 15
FACE_MAX_FRAME_SIZE_MB = 2

# ذخیره تصویر دیباگ فقط برای توسعه
# در تولید نباید فعال شود.
STORE_FACE_DEBUG_IMAGES = False

# برای تست ماک می‌توانید این دو را تغییر دهید:
# FACE_AI_MOCK_SIMILARITY = 0.93
# FACE_AI_MOCK_LIVENESS_PASS = True


# =====================================================================
# تنظیمات جدید نشست احراز هویت چهره
# =====================================================================
FACE_VERIFICATION_TIMEOUT_SECONDS = 60

FACE_GUIDE_MIN_X = 0.20
FACE_GUIDE_MAX_X = 0.80
FACE_GUIDE_MIN_Y = 0.12
FACE_GUIDE_MAX_Y = 0.88

FACE_GUIDE_MIN_WIDTH = 0.22
FACE_GUIDE_MAX_WIDTH = 0.70
FACE_GUIDE_MIN_HEIGHT = 0.22
FACE_GUIDE_MAX_HEIGHT = 0.85

FACE_STABLE_DURATION_MS = 700
FACE_INFERENCE_FPS = 15

HEAD_YAW_TURN_MIN_DEG = 18
HEAD_TURN_HOLD_MS = 250

BLINK_CLOSURE_THRESHOLD = 0.55
BLINK_OPEN_THRESHOLD = 0.25
BLINK_MIN_DURATION_MS = 60
BLINK_MAX_DURATION_MS = 900

FACE_EVIDENCE_MIN_FRAMES = 5
FACE_EVIDENCE_MAX_FRAMES = 12
FACE_EVIDENCE_CAPTURE_INTERVAL_MS = 130


FACE_MEDIAPIPE_MODULE_URL = 'face/mediapipe/vision_bundle.mjs'
FACE_MEDIAPIPE_WASM_BASE = 'face/mediapipe/wasm'
FACE_MEDIAPIPE_MODEL = 'face/mediapipe/face_landmarker.task'


# تنظیمات AI Question Generation
AI_QUESTION_GENERATION = {
    'API_KEY': os.getenv('GAPGPT_API_KEY', 'sk-unnYOTaD7sy4gF5jNc01hkRtE89glT7zRB0nl440MoeucyvN'),
    'BASE_URL': 'https://api.gapgpt.app/v1',
    'MODEL': 'gapgpt-qwen-3.6',
    'MAX_TOKENS': 4096,
    'TEMPERATURE': 0.7,
    'TOP_P': 0.9,
    'TIMEOUT': 120,
    'MAX_RETRIES': 3,
    'RETRY_DELAY': 2,
    'MAX_QUESTIONS_PER_REQUEST': 20,
    'MIN_QUESTIONS_PER_REQUEST': 1,
    'ENABLE_TOPIC_VALIDATION': True,
    'ENABLE_JSON_VALIDATION': True,
}

# Rate Limiting
AI_RATE_LIMIT = {
    'REQUESTS_PER_MINUTE': 10,
    'REQUESTS_PER_HOUR': 100,
}