# Generated by Django 6.1.1 on 2026-09-23 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='امبدینگ چهره به صورت باینری', verbose_name='امبدینگ چهره')),
                ('model_name', models.CharField(default='arcface', max_length=100, verbose_name='نام مدل')),
                ('model_version', models.CharField(blank=True, max_length=100, verbose_name='نسخه مدل')),
                ('embedding_dimension', models.PositiveIntegerField(default=512, verbose_name='بعد امبدینگ')),
                ('source_image', models.CharField(blank=True, max_length=500, verbose_name='مسیر تصویر منبع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'امبدینگ چهره',
                'verbose_name_plural': 'امبدینگ\u200cهای چهره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(choices=[('pending', 'در انتظار'), ('enrolled', 'ثبت شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت ثبت چهره')),
                ('reference_images_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تصاویر مرجع')),
                ('last_enrollment_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان ثبت چهره')),
                ('last_verification_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان احراز هویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پروفایل چهره',
                'verbose_name_plural': 'پروفایل\u200cهای چهره',
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('verified', 'تایید شده'), ('suspicious', 'مشکوک'), ('failed', 'ناموفق'), ('error', 'خطا')], max_length=20, verbose_name='وضعیت')),
                ('similarity_score', models.FloatField(blank=True, null=True, verbose_name='امتیاز تطبیق')),
                ('liveness_passed', models.BooleanField(blank=True, null=True, verbose_name='لایونس تایید شده')),
                ('liveness_confidence', models.FloatField(blank=True, null=True, verbose_name='امتیاز لایونس')),
                ('total_frames', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کل فریم\u200cها')),
                ('valid_frames', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد فریم\u200cهای معتبر')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل عدم موفقیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_verification_logs', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'لاگ احراز هویت چهره',
                'verbose_name_plural': 'لاگ\u200cهای احراز هویت چهره',
                'ordering': ['-created_at'],
            },
        ),
    ]
