# Generated by Django 6.1.1 on 2026-09-25 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='امبدینگ چهره به صورت باینری', verbose_name='امبدینگ چهره')),
                ('model_name', models.CharField(default='arcface', max_length=100, verbose_name='نام مدل')),
                ('model_version', models.CharField(blank=True, max_length=100, verbose_name='نسخه مدل')),
                ('embedding_dimension', models.PositiveIntegerField(default=512, verbose_name='بعد امبدینگ')),
                ('source_image', models.CharField(blank=True, max_length=500, verbose_name='مسیر تصویر منبع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'امبدینگ چهره',
                'verbose_name_plural': 'امبدینگ\u200cهای چهره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(choices=[('pending', 'در انتظار'), ('enrolled', 'ثبت شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت ثبت چهره')),
                ('reference_images_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تصاویر مرجع')),
                ('last_enrollment_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان ثبت چهره')),
                ('last_verification_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان احراز هویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پروفایل چهره',
                'verbose_name_plural': 'پروفایل\u200cهای چهره',
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه نشست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('passed', 'موفق'), ('failed', 'ناموفق'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت نشست')),
                ('challenge_sequence', models.JSONField(blank=True, default=list, verbose_name='ترتیب چالش\u200cها')),
                ('challenge_state', models.JSONField(blank=True, default=dict, verbose_name='وضعیت داخلی چالش\u200cها')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت نشست')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('failure_code', models.CharField(blank=True, default='', max_length=200, verbose_name='کد ناموفق بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verification_sessions', to='dashboard.attendancerequest', verbose_name='درخواست حضور و غیاب')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_verification_sessions', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'نشست احراز هویت چهره',
                'verbose_name_plural': 'نشست\u200cهای احراز هویت چهره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('verified', 'تایید شده'), ('suspicious', 'مشکوک'), ('failed', 'ناموفق'), ('error', 'خطا')], max_length=20, verbose_name='وضعیت')),
                ('similarity_score', models.FloatField(blank=True, null=True, verbose_name='امتیاز تطبیق')),
                ('liveness_passed', models.BooleanField(blank=True, null=True, verbose_name='لایونس تایید شده')),
                ('liveness_confidence', models.FloatField(blank=True, null=True, verbose_name='امتیاز لایونس')),
                ('total_frames', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کل فریم\u200cها')),
                ('valid_frames', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد فریم\u200cهای معتبر')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل عدم موفقیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('challenge_result', models.JSONField(blank=True, null=True, verbose_name='نتیجه چالش کلاینت (فقط تله\u200cمتری)')),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پردازش (میلی\u200cثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_verification_logs', to='dashboard.attendancerequest', verbose_name='درخواست حضور و غیاب')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_verification_logs', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='face.faceverificationsession', verbose_name='نشست احراز هویت')),
            ],
            options={
                'verbose_name': 'لاگ احراز هویت چهره',
                'verbose_name_plural': 'لاگ\u200cهای احراز هویت چهره',
                'ordering': ['-created_at'],
            },
        ),
    ]
