# Generated by Django 6.1.1 on 2026-09-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_attendanceresponse_attempts_and_more'),
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverificationlog',
            name='attendance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_verification_logs', to='dashboard.attendancerequest', verbose_name='درخواست حضور و غیاب'),
        ),
    ]
