# Generated by Django 6.1.1 on 2026-09-26 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_classroom_school'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('material_type', models.CharField(choices=[('FILE', 'فایل'), ('LINK', 'لینک'), ('VIDEO', 'ویدیو'), ('DOCUMENT', 'سند')], default='FILE', max_length=20, verbose_name='نوع محتوا')),
                ('file', models.FileField(blank=True, null=True, upload_to='session_materials/', verbose_name='فایل')),
                ('external_url', models.URLField(blank=True, default='', verbose_name='لینک خارجی')),
                ('visible_to_students', models.BooleanField(default=True, verbose_name='قابل مشاهده برای دانش\u200cآموز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='dashboard.classsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'محتوای آموزشی جلسه',
                'verbose_name_plural': 'محتوای آموزشی جلسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFaceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='دلیل درخواست')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='یادداشت بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_face_changes', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'درخواست تغییر چهره',
                'verbose_name_plural': 'درخواست\u200cهای تغییر چهره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شماره درخواست')),
                ('request_type', models.CharField(choices=[('ATTENDANCE_CORRECTION', 'اصلاح حضور و غیاب'), ('ATTENDANCE_PROBLEM', 'مشکل در حضور و غیاب'), ('GRADE_APPEAL', 'اعتراض به نمره'), ('ANSWER_REVIEW', 'بررسی پاسخ'), ('STATUS_REVIEW', 'بازبینی وضعیت آموزشی'), ('FACE_VERIFICATION_REVIEW', 'بررسی مشکل احراز هویت'), ('FACE_CHANGE_REQUEST', 'درخواست تغییر چهره'), ('GENERAL', 'سایر')], max_length=30, verbose_name='نوع درخواست')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='شرح درخواست')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد'), ('URGENT', 'فوری')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('OPEN', 'ثبت شده'), ('IN_REVIEW', 'در حال بررسی'), ('NEEDS_INFO', 'نیازمند اطلاعات'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('RESOLVED', 'حل شده'), ('CANCELLED', 'لغو شده')], default='OPEN', max_length=20, verbose_name='وضعیت')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حل')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='یادداشت حل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_student_requests', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع به')),
                ('related_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='teacher.assessment', verbose_name='ارزیابی مرتبط')),
                ('related_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='dashboard.attendanceresponse', verbose_name='حضور مرتبط')),
                ('related_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='dashboard.classroom', verbose_name='کلاس مرتبط')),
                ('related_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='dashboard.question', verbose_name='سوال مرتبط')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='dashboard.classsession', verbose_name='جلسه مرتبط')),
                ('related_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='teacher.homeworksubmission', verbose_name='ارسال مرتبط')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'درخواست دانش\u200cآموز',
                'verbose_name_plural': 'درخواست\u200cهای دانش\u200cآموزان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualSessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_url', models.URLField(blank=True, default='', verbose_name='لینک کلاس مجازی')),
                ('meeting_provider', models.CharField(blank=True, default='', max_length=100, verbose_name='سرویس\u200cدهنده')),
                ('meeting_start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع کلاس مجازی')),
                ('meeting_end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان کلاس مجازی')),
                ('meeting_id', models.CharField(blank=True, default='', max_length=200, verbose_name='شناسه جلسه')),
                ('meeting_password', models.CharField(blank=True, default='', max_length=100, verbose_name='رمز جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_info', to='dashboard.classsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'اطلاعات کلاس مجازی',
                'verbose_name_plural': 'اطلاعات کلاس\u200cهای مجازی',
            },
        ),
    ]
